
export interface IProduct{
    name: string,
    price: number,
    coverImgUrl: string,
    productImgUrls: string[],
    type: string,
    popular?: boolean,
    discountPrice?: number,
    description: string,
    brand: string,
    itemCode: string,
    limited?: number,
    inStock: number,
}
export interface IProductData{
    [key: string]: IProduct,
}
const sampleProductDetailData: IProduct = {
    name: '玉玺 Yuxi',
    price: 23888,
    coverImgUrl: 'PSX-01-cover.jpg',
    productImgUrls: [''],
    itemCode:'PSX-01',
    description: '',
    type: 'cue',
    brand: 'Peri',
    limited: 99,
    inStock: 0,

}

export const productDetailData: IProductData = {
    'PSX-01':  { name: '玉玺 Yuxi',
                    price: 23888,
                    coverImgUrl: 'PSX-01-cover.jpg',
                    productImgUrls: ['PSX-01-1.jpg', 'PSX-01-2.jpg','PSX-01-3.jpg','PSX-01-4.jpg','PSX-01-5.jpg','PSX-01-6.jpg','PSX-01-7.jpg','PSX-01-8.jpg','PSX-01-9.jpg',],
                    itemCode:'PSX-01',
                    description: '皮尔力再次超越自我，推出全新旗舰之作, 皮尔力·玉玺, 以王者之名，领风云所向, 球杆不仅使用顶级材料、专利科技技术, 还有前所未有的外观设计，种种超凡之举<br/><br/>如今全部荟萃一身，造就您的至尊体验<br/><br/>皮尔力·玉玺，独享至尊<br/><br/>皮尔力·玉玺身上的每一个基因，都追求着一种整体之美。原装配置P8和P20形态前支，均为自主研发的科技前支，选材用料非常严苛。全部甄选AA级北美硬枫木，五年以上恒温恒湿自然脱水稳定木性，再优中择优，让您可以从容应对多种局面，全身心地享受每一次击球瞬间，以性能让挑战臣服。后把中轮上奢华的金色“双K”标识代表皮尔力品牌球杆的最高级别是锋芒，更是内涵, 刚劲挺拔的身姿与睥睨天下的气场相得益彰，这正是皮尔力·玉玺独有风范的精髓所在。初见精美绝伦的后把工艺，考究的用料和做工即令人仰慕，特别甄选贵族A级黑檀木为主料，精致奢雅的雕刻镶嵌图案汲取灵感自大千世界，将中国传统“如意”元素汇集其中，祈福禳安，吉祥如意，彰显古风雅致。极赋艺术性的中国花卉设计，仅仅约3.3*1.1cm的花卉图案就有28处镶嵌。悉心选用珍惜的郁金香木、黄花梨、五彩贝壳等材料，嵌于典雅而别致的后把之中，这一独特的饰面设计配搭黑色主体，丰富了层次感，于方寸间弥漫奢华美感，从细节彰显不凡品位。皮尔力·玉玺融合了一系列皮尔力独有的设计，后把配饰“PERI”品牌标志，为富有韵味的后把增添了耀目的点缀。<br/><br/>现代科技融合出众设计，皮尔力·玉玺后把内部十字碳纤通体专利技术，让每一次击球体验得到真切的提升<br/><br/>皮尔力·玉玺<br/><br/>为您诠释卓尔不群的风采, 他不仅仅是一支球杆，他更是您的世界的一部分, 外在：以傲人气度征服人心, 内修：拓一方天地，笑瞰风云，尽显尊崇本色<br/><br/>配置：皮尔力·玉玺球杆+双前支+双加长把+黄金蟒杆箱全套配件',
                    type: 'cue',
                    brand: 'Peri',
                    limited: 99,
                    inStock: 0,
    },
    'PSX-02':  { name: '天王 Tianwang',
                    price: 15888,
                    coverImgUrl: 'PSX-02-cover.jpg',
                    productImgUrls: ['PSX-02-1.jpg', 'PSX-02-2.jpg','PSX-02-3.jpg','PSX-02-4.jpg','PSX-02-5.jpg','PSX-02-6.jpg','PSX-02-7.jpg','PSX-02-8.jpg','PSX-02-9.jpg','PSX-02-10.jpg','PSX-02-11.jpg',],
                    itemCode:'PSX-02',
                    description: '天王级硬核品质，彰显您的王者身份<br/><br/>源于对设计苛刻追求，皮尔力始终坚持匠心手作，让生而不凡的“皮尔力·天王”于千篇一律中脱颖而出，才能符合您高人一等的眼光。奢雅而硬朗，慕然一瞥，已美至惊鸿。<br/><br/>每一支“皮尔力·天王”球杆需要两年的生产周期，从选料用材、雕刻镶嵌、打磨喷漆到配套包装，每一个步骤严格遵循A级标准。<br/><br/> 至臻A级黑檀木为主体的后把，采用进口CNC高精密雕刻技术，实现繁琐细致的雕刻镶嵌工艺。并且严格把控每一块嵌镶的重量，让多面嵌镶实现平衡统一，确保重量、重心不偏移。每一支球杆都必须一次成型，任何一处细微镶嵌出现0.06mm的偏差，一律淘汰。让您在享受奢华外观的同时，更能体验手臂延伸般的顺畅打感。<br/><br/> 考究的细节处理，备显尊崇，贵族气质的金属铜镶嵌，迅捷之速绽放眼前。金属铜与木制的衔接光滑紧实无毛刺，每一处铜片都要经过数小时的手工打磨抛光，达到机器无法实现的镜面金属光泽。<br/><br/> 握把采用市面上非常罕见的环雕工艺，每一根雕刻线条900°盘旋于握把之上，黑白明暗交错间演绎绚丽灵动，所触及之处细腻顺滑。<br/><br/> 内外兼修，性能致上，奢华球杆新定义<br/><br/>皮尔力·天王球杆实现重大的改变和突破，代表皮尔力高级别的金标“双K”，王者风范不言而喻。<br/><br/>配置金标的P8前支和P20前支，每一支球杆的密度、硬度等数十项参数逐一经过人工检测，真正做到优中择优，并且每一支前支与后把都再次经过人工匹配测试，前后的传动更均匀透彻，确保每一支球杆的性能发挥到极致。<br/><br/> 皮尔力匠心倾注、不断进化，针对本款球杆定制升级了后把传力加速系统，能更好的发挥木制的天然性能，实现重量平衡、动能平衡，性能优势更加凸显：打感通透，反应灵敏，杆法效果明显。<br/><br/> 以王者之名，于不经意间，让您尽显尊崇本色<br/><br/>“天王”对代勇来说意味着一种荣誉、一份执着，一种肯定，22年的职业生涯，突破一个又一个极限，才成就了今天的自己，纵行台球天地，无愧挚爱初心。<br/><br/>“中式天王”代勇将毕生所学倾注到这款球杆之中，把自己对台球的理解汇集到这支球杆的精髓中，同时也凝聚百位匠人的心血，铸就一支真正的中式球杆。<br/><br/>“冠军只有一个，人生却可以丰富多彩，这也许就是台球带给我宝贵的财富。用我有限的精力去做更多有意义的事情，让更多的人喜欢台球，享受台球。也希望这支球杆在每一位使用者手中仍然不断地被塑造，成为荣誉的武器，尊贵的象征，王者的代表。”<br/><br/>',
                    type: 'cue',
                    brand: 'Peri',
                    limited: 99,
                    inStock: 0,
    },
    'PWX-02':  { name: '黄金甲 HuangJinJia',
                    price: 15688,
                    coverImgUrl: 'PWX-02-cover.jpg',
                    productImgUrls: ['PWX-02-1.jpg', 'PWX-02-2.jpg','PWX-02-3.jpg','PWX-02-4.jpg','PWX-02-5.jpg','PWX-02-6.jpg','PWX-02-7.jpg','PWX-02-8.jpg','PWX-02-9.jpg',],
                    itemCode:'PWX-02',
                    description: 'Please find the description on the image for more information',
                    type: 'cue',
                    brand: 'Peri',
                    inStock: 0,
    },
    'PT-SK1':  { name: '金字塔 JinZiTa',
                    price: 8688,
                    coverImgUrl: 'PT-SK1-cover.jpg',
                    productImgUrls: ['PT-SK1-1.jpg', 'PT-SK1-2.jpg','PT-SK1-3.jpg','PT-SK1-4.jpg','PT-SK1-5.jpg','PT-SK1-6.jpg','PT-SK1-7.jpg',],
                    itemCode:'PT-SK1',
                    description: 'Please find the description on the image for more information',
                    type: 'cue',
                    brand: 'Peri',
                    inStock: 0,
    },
    'ELEGANCE-LV-04':  { name: '静远 ELEGANCE LV-04',
    price: 1588,
    coverImgUrl: 'ELEGANCE-LV-04-cover.jpg',
    productImgUrls: ['ELEGANCE-LV-04-1.jpg', 'ELEGANCE-LV-04-2.jpg','ELEGANCE-LV-04-3.jpg','ELEGANCE-LV-04-4.jpg','ELEGANCE-LV-04-5.jpg','ELEGANCE-LV-04-6.jpg','ELEGANCE-LV-04-7.jpg',],
    itemCode:'ELEGANCE-LV-04',
    description: 'Please find the description on the image for more information',
    type: 'cue',
    brand: 'Peri',
    inStock: 0,
    },
    'ELEGANCE-LV-03':  { name: '静远 ELEGANCE LV-03',
    price: 1299,
    coverImgUrl: 'ELEGANCE-LV-03-cover.jpg',
    productImgUrls: ['ELEGANCE-LV-03-1.jpg', 'ELEGANCE-LV-03-2.jpg','ELEGANCE-LV-03-3.jpg','ELEGANCE-LV-03-4.jpg','ELEGANCE-LV-03-5.jpg','ELEGANCE-LV-03-6.jpg',],
    itemCode:'ELEGANCE-LV-03',
    description: 'Please find the description on the image for more information',
    type: 'cue',
    brand: 'Peri',
    inStock: 0,
    },
    'ELEGANCE-LV-02':  { name: '静远 ELEGANCE LV-02',
    price: 1266,
    coverImgUrl: 'ELEGANCE-LV-02-cover.jpg',
    productImgUrls: ['ELEGANCE-LV-02-1.jpg', 'ELEGANCE-LV-02-2.jpg','ELEGANCE-LV-02-3.jpg','ELEGANCE-LV-02-4.jpg','ELEGANCE-LV-02-5.jpg','ELEGANCE-LV-02-6.jpg','ELEGANCE-LV-02-7.jpg',],
    itemCode:'ELEGANCE-LV-02',
    description: 'Please find the description on the image for more information',
    type: 'cue',
    brand: 'Peri',
    inStock: 0,
    },
    'ELEGANCE-LV-01':  { name: '静远 ELEGANCE LV-01',
    price: 1266,
    coverImgUrl: 'ELEGANCE-LV-01-cover.jpg',
    productImgUrls: ['ELEGANCE-LV-01-1.jpg', 'ELEGANCE-LV-01-2.jpg','ELEGANCE-LV-01-3.jpg','ELEGANCE-LV-01-4.jpg','ELEGANCE-LV-01-5.jpg','ELEGANCE-LV-01-6.jpg','ELEGANCE-LV-01-7.jpg',],
    itemCode:'ELEGANCE-LV-01',
    description: 'Please find the description on the image for more information',
    type: 'cue',
    brand: 'Peri',
    inStock: 0,
    },
    'ELEGANCE-VK-01':  { name: '静远 ELEGANCE VK-01',
    price: 849,
    coverImgUrl: 'ELEGANCE-VK-01-cover.jpg',
    productImgUrls: ['ELEGANCE-VK-01-1.jpg', 'ELEGANCE-VK-01-2.jpg','ELEGANCE-VK-01-3.jpg','ELEGANCE-VK-01-4.jpg','ELEGANCE-VK-01-5.jpg','ELEGANCE-VK-01-6.jpg','ELEGANCE-VK-01-7.jpg',],
    itemCode:'ELEGANCE-VK-01',
    description: 'Please find the description on the image for more information',
    type: 'cue',
    brand: 'Peri',
    inStock: 0,
    },
    'ELEGANCE-VK-02':  { name: '静远 ELEGANCE VK-02',
    price: 849,
    coverImgUrl: 'ELEGANCE-VK-02-cover.jpg',
    productImgUrls: ['ELEGANCE-VK-02-1.jpg', 'ELEGANCE-VK-02-2.jpg','ELEGANCE-VK-02-3.jpg','ELEGANCE-VK-02-4.jpg','ELEGANCE-VK-02-5.jpg','ELEGANCE-VK-02-6.jpg','ELEGANCE-VK-02-7.jpg','ELEGANCE-VK-02-8.jpg',],
    itemCode:'ELEGANCE-VK-02',
    description: 'Please find the description on the image for more information',
    type: 'cue',
    brand: 'Peri',
    inStock: 0,
    },
    'ELEGANCE-VK-03':  { name: '静远 ELEGANCE VK-03',
    price: 849,
    coverImgUrl: 'ELEGANCE-VK-03-cover.jpg',
    productImgUrls: ['ELEGANCE-VK-03-1.jpg', 'ELEGANCE-VK-03-2.jpg','ELEGANCE-VK-03-3.jpg','ELEGANCE-VK-03-4.jpg','ELEGANCE-VK-03-5.jpg','ELEGANCE-VK-03-6.jpg','ELEGANCE-VK-03-7.jpg','ELEGANCE-VK-03-8.jpg','ELEGANCE-VK-03-9.jpg',],
    itemCode:'ELEGANCE-VK-03',
    description: 'Please find the description on the image for more information',
    type: 'cue',
    brand: 'Peri',
    inStock: 0,
    },
    'ELEGANCEIII-V30-04':  { name: '静远 ELEGANCEIII V30-04',
    price: 1188,
    coverImgUrl: 'ELEGANCEIII-V30-04-cover.jpg',
    productImgUrls: ['ELEGANCEIII-V30-04-1.jpg', 'ELEGANCEIII-V30-04-2.jpg','ELEGANCEIII-V30-04-3.jpg','ELEGANCEIII-V30-04-4.jpg',],
    itemCode:'ELEGANCEIII-V30-04',
    description: '皮尔力·静远V30，是皮尔力·静远V20的升级款。<br/><br/>素面球杆爱好者的福音来了！<br/><br/>当年“静远V20”凭借素面工艺与超强性价比，曾是三四千元中式球杆中一直处于供不应求的产品，它的停产让很多爱好者没有机会再得到自己梦寐以求的球杆，现在它的升级款来了！<br/><br/>素得更高端  配置更强大<br/><br/>产品亮点经典设计语言? V30继承了皮尔力·静远经典[素尔不凡]的设计风格，整体纯正雅致的素色，简约时尚，本次添加的雕刻的设计直接让这系列球杆奢华感再度提升！而两款皮把、两款光把的设计，让用户更有选择空间。<br/><br/>P20前支与Dymond wood木料前臂的碰撞 动能强 击打稳，静远一直是大众最喜欢的皮尔力球杆系列之一。这次为了提升静远V30的打感，皮尔力制杆师可以说将目前品牌前沿技术都凝用在这款球杆上了。它的配置远远超过了它的市场价。<br/><br/>配备 性能卓越的P20前支：硬度、弹性兼具，几乎无让点。木料优选，硬度有保证。整体特殊的形态使视觉瞄准，以及击打犀利度提高。12.5mm的杆头击打白球锁点精确。鹰眼皮头保证了击打瞬间杆头着力在母球上更具摩擦效果，鹰眼自带的弹适空间也让力反应更活，整体达到球杆击打接近理想状态。<br/><br/>在前臂的部分加入了Dymond wood木料：这种密度高、硬度强、质地轻盈而抗击打的木料，使用直接提高了球杆硬度，将原本球杆最薄弱的环节变成快车道，明显提高了传力效果，并在长久使用过程中具有显著抗弯性。<br/><br/>',
    type: 'cue',
    brand: 'Peri',
    inStock: 0,
    },
    'ELEGANCEIII-V30-05':  { name: '静远 ELEGANCEIII V30-05',
    price: 1088,
    coverImgUrl: 'ELEGANCEIII-V30-05-cover.jpg',
    productImgUrls: ['ELEGANCEIII-V30-05-1.jpg', 'ELEGANCEIII-V30-05-2.jpg','ELEGANCEIII-V30-05-3.jpg','ELEGANCEIII-V30-05-4.jpg','ELEGANCEIII-V30-05-5.jpg','ELEGANCEIII-V30-05-6.jpg',],
    itemCode:'ELEGANCEIII-V30-05',
    description: 'Please find the description on the image for more information',
    type: 'cue',
    brand: 'Peri',
    inStock: 0,
    },
    'ELEGANCEIII-V30-03':  { name: '静远 ELEGANCEIII V30-03',
    price: 1188,
    coverImgUrl: 'ELEGANCEIII-V30-03-cover.jpg',
    productImgUrls: ['ELEGANCEIII-V30-03-1.jpg', 'ELEGANCEIII-V30-03-2.jpg','ELEGANCEIII-V30-03-3.jpg','ELEGANCEIII-V30-03-4.jpg',],
    itemCode:'ELEGANCEIII-V30-03',
    description: '皮尔力·静远V30，是皮尔力·静远V20的升级款。<br/><br/>素面球杆爱好者的福音来了！<br/><br/>当年“静远V20”凭借素面工艺与超强性价比，曾是三四千元中式球杆中一直处于供不应求的产品，它的停产让很多爱好者没有机会再得到自己梦寐以求的球杆，现在它的升级款来了！<br/><br/>素得更高端  配置更强大<br/><br/>产品亮点经典设计语言? V30继承了皮尔力·静远经典[素尔不凡]的设计风格，整体纯正雅致的素色，简约时尚，本次添加的雕刻的设计直接让这系列球杆奢华感再度提升！而两款皮把、两款光把的设计，让用户更有选择空间。<br/><br/>P20前支与Dymond wood木料前臂的碰撞 动能强 击打稳，静远一直是大众最喜欢的皮尔力球杆系列之一。这次为了提升静远V30的打感，皮尔力制杆师可以说将目前品牌前沿技术都凝用在这款球杆上了。它的配置远远超过了它的市场价。<br/><br/>配备 性能卓越的P20前支：硬度、弹性兼具，几乎无让点。木料优选，硬度有保证。整体特殊的形态使视觉瞄准，以及击打犀利度提高。12.5mm的杆头击打白球锁点精确。鹰眼皮头保证了击打瞬间杆头着力在母球上更具摩擦效果，鹰眼自带的弹适空间也让力反应更活，整体达到球杆击打接近理想状态。<br/><br/>在前臂的部分加入了Dymond wood木料：这种密度高、硬度强、质地轻盈而抗击打的木料，使用直接提高了球杆硬度，将原本球杆最薄弱的环节变成快车道，明显提高了传力效果，并在长久使用过程中具有显著抗弯性。<br/><br/>',
    type: 'cue',
    brand: 'Peri',
    inStock: 0,
    },
    'ELEGANCEIII-V30-01':  { name: '静远 ELEGANCEIII V30-01',
    price: 1168,
    coverImgUrl: 'ELEGANCEIII-V30-01-cover.jpg',
    productImgUrls: ['ELEGANCEIII-V30-01-1.jpg', 'ELEGANCEIII-V30-01-2.jpg','ELEGANCEIII-V30-01-3.jpg','ELEGANCEIII-V30-01-4.jpg',],
    itemCode:'ELEGANCEIII-V30-01',
    description: '皮尔力·静远V30，是皮尔力·静远V20的升级款。<br/><br/>素面球杆爱好者的福音来了！<br/><br/>当年“静远V20”凭借素面工艺与超强性价比，曾是三四千元中式球杆中一直处于供不应求的产品，它的停产让很多爱好者没有机会再得到自己梦寐以求的球杆，现在它的升级款来了！<br/><br/>素得更高端  配置更强大<br/><br/>产品亮点经典设计语言? V30继承了皮尔力·静远经典[素尔不凡]的设计风格，整体纯正雅致的素色，简约时尚，本次添加的雕刻的设计直接让这系列球杆奢华感再度提升！而两款皮把、两款光把的设计，让用户更有选择空间。<br/><br/>P20前支与Dymond wood木料前臂的碰撞 动能强 击打稳，静远一直是大众最喜欢的皮尔力球杆系列之一。这次为了提升静远V30的打感，皮尔力制杆师可以说将目前品牌前沿技术都凝用在这款球杆上了。它的配置远远超过了它的市场价。<br/><br/>配备 性能卓越的P20前支：硬度、弹性兼具，几乎无让点。木料优选，硬度有保证。整体特殊的形态使视觉瞄准，以及击打犀利度提高。12.5mm的杆头击打白球锁点精确。鹰眼皮头保证了击打瞬间杆头着力在母球上更具摩擦效果，鹰眼自带的弹适空间也让力反应更活，整体达到球杆击打接近理想状态。<br/><br/>在前臂的部分加入了Dymond wood木料：这种密度高、硬度强、质地轻盈而抗击打的木料，使用直接提高了球杆硬度，将原本球杆最薄弱的环节变成快车道，明显提高了传力效果，并在长久使用过程中具有显著抗弯性。<br/><br/>',
    type: 'cue',
    brand: 'Peri',
    inStock: 0,
    },
}

export const limitedProduct: string[] = [
    'PSX-01', 'PSX-02', 'PWX-02', 'PT-SK1'
]
export const eleganceSeriesProduct: string[] = [
    'ELEGANCE-LV-04', 'ELEGANCE-LV-03', 'ELEGANCE-LV-02', 'ELEGANCE-LV-01', 'ELEGANCE-VK-01', 'ELEGANCE-VK-02', 'ELEGANCE-VK-03',
    'ELEGANCEIII-V30-04', 'ELEGANCEIII-V30-05', 'ELEGANCEIII-V30-03', 'ELEGANCEIII-V30-01',
]

export function getProductDataByProductCodes(itemCodes: string[]): IProduct[]{
    let tempArr: IProduct[] = [];
    itemCodes.forEach((itemCode)=>tempArr.push(productDetailData[itemCode]));
    return tempArr;
}
